/**
 * segment_stubs.c - Stub definitions for N64 ROM segment symbols
 * and boot.c assembly functions.
 *
 * On N64, these are generated by the linker script. On PC we provide
 * the actual ROM offset values extracted from the N64 ELF so that
 * game code can read data from the loaded ROM image.
 *
 * IMPORTANT: These symbols are declared as `extern u32 *name` in bondgame.h.
 * On N64, they're linker symbols where &name == the ROM offset.
 * On PC, they're variables where the VALUE contains the ROM offset.
 * The PC romCopy (in ramrom.c) handles this difference.
 */
#include <ultra64.h>

/* --- ROM/RAM segment boundary symbols --- */
/* Values from: nm build/u/ge007.u.elf */

u32 _bssSegmentStart     = 0x8005d2e0;
u32 _bssSegmentEnd       = 0x8008e360;

u32 _codeSegmentStart    = 0x70000450;
u32 _codeSegmentEnd      = 0x70020d90;
u32 _codeSegmentRomStart = 0x00001050;
u32 _codeSegmentRomEnd   = 0x00021990;

u32 _csegmentSegmentStart = 0x80020d90;
u32 _csegmentSegmentEnd   = 0x8005d2e0;
u32 _cdataSegmentRomStart = 0x00021990;
u32 _cdataSegmentRomEnd   = 0x00033590;

u32 _inflateSegmentRomStart = 0x00033590;
u32 _inflateSegmentRomEnd   = 0x00034b30;

u32 _gameSegmentRomStart = 0x00034b30;
u32 _gameSegmentRomEnd   = 0x00117880;

u32 _animation_dataSegmentRomStart = 0x0028e980;
u32 _animation_dataSegmentStart    = 0x00000000;
u32 _animation_dataSegmentEnd      = 0x0000e7e0;

u32 _animation_entriesSegmentRomStart = 0x00124ac0;

u32 _alt_startSegmentRomStart = 0x00101000;
u32 _alt_startSegmentStart    = 0x70100400;

u32 _stacksSegmentStart = 0x803ab400;

/* Audio segment symbols used by music.c */
u32 _sfxtblSegmentRomStart         = 0x002f19a0;
u32 _sfxctlSegmentRomStart         = 0x002ebde0;
u32 _instrumentstblSegmentRomStart = 0x003b87f0;
u32 _instrumentsctlSegmentRomStart = 0x003b4450;
u32 _musicsampletblSegmentRomStart = 0x00419790;

/* --- boot.c assembly function stubs --- */
/* boot.c is pure MIPS asm; we stub its exported functions here. */

u32 get_csegmentSegmentStart(void)  { return 0x80020d90; }
u32 get_cdataSegmentRomStart(void)  { return 0x00021990; }
u32 get_cdataSegmentRomEnd(void)    { return 0x00033590; }
u32 get_inflateSegmentRomStart(void){ return 0x00033590; }
u32 get_inflateSegmentRomEnd(void)  { return 0x00034b30; }

u32 jump_decompressfile(u32 source, u32 target, u32 buffer) {
    (void)source; (void)target; (void)buffer;
    return 0;
}

/* From tlb_hardwire.s */
void initTLBPrepareContext(void) {}

/* --- Additional segment symbols found during link --- */

/* Font segments */
u32 _efontchardataSegmentRomStart = 0x00123040;
u32 _jfontchardataSegmentRomStart = 0x00117940;
u32 _fontdlSegmentRomStart = 0x00117880;
u32 _fontdlSegmentRomEnd   = 0x00117940;

/* Font bank segments */
u32 _fontbankgothicSegmentRomStart  = 0x002e63f0;
u32 _fontbankgothicSegmentRomEnd    = 0x002e88a0;
u32 _fontzurichboldSegmentRomStart  = 0x002e88a0;
u32 _fontzurichboldSegmentRomEnd    = 0x002ebde0;

/* Global image table segments */
u32 _GlobalimagetableSegmentRomStart = 0x0029d160;
u32 _GlobalimagetableSegmentStart    = 0x02000000;
u32 _GlobalimagetableSegmentEnd      = 0x02001400;

/* Images segment */
u32 _imagesSegmentRomStart = 0x008f7df0;

/* Rareware logo segments */
u32 _rarewarelogoSegmentRomStart = 0x0029e560;
u32 _rarewarelogoSegmentRomEnd   = 0x002a4d50;
u32 _rarewarelogoSegmentStart    = 0x02000000;
u32 _rarewarelogoSegmentEnd      = 0x020067f0;

/* Ramrom segment */
u32 _ramromDam1SegmentRomStart = 0x002bf2d0;

/* --- Ramrom demo/replay data stubs --- */
u32 ramrom_Dam_1 = 0;
u32 ramrom_Dam_2 = 0;
u32 ramrom_Facility_1 = 0;
u32 ramrom_Facility_2 = 0;
u32 ramrom_Facility_3 = 0;
u32 ramrom_Runway_1 = 0;
u32 ramrom_Runway_2 = 0;
u32 ramrom_BunkerI_1 = 0;
u32 ramrom_BunkerI_2 = 0;
u32 ramrom_Silo_1 = 0;
u32 ramrom_Silo_2 = 0;
u32 ramrom_Frigate_1 = 0;
u32 ramrom_Frigate_2 = 0;
u32 ramrom_Train = 0;
