/* ROM-free compile-time lock on N64 struct layouts (S-tier Task 0.7,
 * FID-0035 + first half of FID-0036).
 *
 * The port reads ROM data (the StandTile navmesh, PROPDEF setup records)
 * straight into these structs, relying on the ORIGINAL N64 field offsets. That
 * layout is held together ONLY by two compiler flags applied to the game target
 * (CMakeLists.txt:707+): `-fms-extensions` (to parse bondtypes.h's `inherits`
 * anonymous-struct idiom) and `-mno-ms-bitfields` (to force SysV/Itanium
 * bit-field packing on every platform). MinGW/GCC on Windows DEFAULT to
 * -mms-bitfields, which repacks mixed bit-field structs — this is exactly what
 * crashed v0.3.2 on Windows: StandTile got repadded and the stan navmesh read
 * out of bounds.
 *
 * The `_Static_assert`s below fire at COMPILE time, so any compiler/flag drift
 * that changes an asserted size or offset fails the BUILD instead of silently
 * corrupting memory at runtime. Expected values are the current known-good
 * build's actual sizeof/offsetof (identical on macOS clang and MinGW GCC under
 * -mno-ms-bitfields — verified with tools/mingw_cross_check.sh's toolchain), so
 * they lock in the -mno-ms-bitfields layout. NOTE: the offsets differ from the
 * N64-doc offsets in bondtypes.h comments (e.g. TankRecord `rect` is documented
 * at 0x84 but sits at 0x98 here) because 64-bit PC pointers expand
 * ObjectRecord from 0x80 to 0x90 — these asserts lock the ACTUAL PC layout.
 *
 * Regenerate expected values with: tools/fidelity/gen_struct_asserts.py
 * (paste its output over the generated block below; then review the diff — a
 * changed value is either an intentional layout change or a drift finding).
 *
 * This TU must be compiled with the same GAME_DEFINES + -fms-extensions +
 * -mno-ms-bitfields as the ge007 target (see CMakeLists.txt registration). The
 * runtime body is trivial — the real check already happened at compile time. */

#include <stddef.h>
#include <stdio.h>

#include "bondtypes.h"
#include "bondview.h"   /* struct hand / struct player — FID-0085 hand-matrix lock */

/* ==== BEGIN generated by tools/fidelity/gen_struct_asserts.py ==== */
/* PROPDEF record sizes — sizepropdef_pc_bytes (prop.c) and the
 * NATIVE_PORT arm of sizepropdef (loadobjectmodel.c).
 *
 * W1.5 ILP32 (wasm32) twins: every struct below that (directly, or via the
 * `inherits`/anonymous-member chain up through ObjectRecord/PropDefHeaderRecord)
 * contains a pointer member shrinks under ILP32 (4B pointers, 4B max alignment
 * instead of LP64's 8B pointers / 8B alignment) — hand-derived field-by-field
 * below and confirmed by a clean first-attempt wasm32 compile (every ILP32
 * constant matched the compiler's sizeof/offsetof on the first try). The LP64
 * arm of every gated assert is character-identical to the pre-existing assert,
 * so native builds are byte-identical. Structs with NO pointer in their chain
 * (GlobalDoorScaleRecord, objective_entry, the StandTile/StandFile navmesh
 * family) are width-INVARIANT and left ungated. */
#if __SIZEOF_POINTER__ == 8
_Static_assert(sizeof(GuardRecord) == 32, "sizeof(GuardRecord) drifted from locked 32 (0x20)");
_Static_assert(sizeof(DoorRecord) == 296, "sizeof(DoorRecord) drifted from locked 296 (0x128)");
_Static_assert(sizeof(GlobalDoorScaleRecord) == 8, "sizeof(GlobalDoorScaleRecord) drifted from locked 8 (0x8)");
_Static_assert(sizeof(ObjectRecord) == 144, "sizeof(ObjectRecord) drifted from locked 144 (0x90)");
_Static_assert(sizeof(WeaponObjRecord) == 160, "sizeof(WeaponObjRecord) drifted from locked 160 (0xa0)");
_Static_assert(sizeof(KeyRecord) == 152, "sizeof(KeyRecord) drifted from locked 152 (0x98)");
_Static_assert(sizeof(TintedGlassRecord) == 168, "sizeof(TintedGlassRecord) drifted from locked 168 (0xa8)");
_Static_assert(sizeof(BodyArmourRecord) == 152, "sizeof(BodyArmourRecord) drifted from locked 152 (0x98)");
_Static_assert(sizeof(MonitorObjRecord) == 288, "sizeof(MonitorObjRecord) drifted from locked 288 (0x120)");
_Static_assert(sizeof(MultiMonitorObjRecord) == 664, "sizeof(MultiMonitorObjRecord) drifted from locked 664 (0x298)");
_Static_assert(sizeof(AutogunRecord) == 248, "sizeof(AutogunRecord) drifted from locked 248 (0xf8)");
_Static_assert(sizeof(MultiAmmoCrateRecord) == 200, "sizeof(MultiAmmoCrateRecord) drifted from locked 200 (0xc8)");
_Static_assert(sizeof(VehichleRecord) == 208, "sizeof(VehichleRecord) drifted from locked 208 (0xd0)");
_Static_assert(sizeof(AircraftRecord) == 208, "sizeof(AircraftRecord) drifted from locked 208 (0xd0)");
_Static_assert(sizeof(TankRecord) == 248, "sizeof(TankRecord) drifted from locked 248 (0xf8)");
_Static_assert(sizeof(CCTVRecord) == 272, "sizeof(CCTVRecord) drifted from locked 272 (0x110)");
_Static_assert(sizeof(AmmoCrateRecord) == 152, "sizeof(AmmoCrateRecord) drifted from locked 152 (0x98)");
_Static_assert(sizeof(SafeObjectRecord) == 40, "sizeof(SafeObjectRecord) drifted from locked 40 (0x28)");
_Static_assert(sizeof(TagObjectRecord) == 24, "sizeof(TagObjectRecord) drifted from locked 24 (0x18)");
_Static_assert(sizeof(RenameObjectRecord) == 48, "sizeof(RenameObjectRecord) drifted from locked 48 (0x30)");
_Static_assert(sizeof(LinkRecord) == 32, "sizeof(LinkRecord) drifted from locked 32 (0x20)");
_Static_assert(sizeof(SwitchRecord) == 32, "sizeof(SwitchRecord) drifted from locked 32 (0x20)");
_Static_assert(sizeof(LockDoorRecord) == 32, "sizeof(LockDoorRecord) drifted from locked 32 (0x20)");
_Static_assert(sizeof(struct setup_objective_text) == 24, "sizeof(struct setup_objective_text) drifted from locked 24 (0x18)");
_Static_assert(sizeof(struct criteria_roomentered) == 24, "sizeof(struct criteria_roomentered) drifted from locked 24 (0x18)");
_Static_assert(sizeof(struct criteria_deposit) == 24, "sizeof(struct criteria_deposit) drifted from locked 24 (0x18)");
_Static_assert(sizeof(struct criteria_picture) == 24, "sizeof(struct criteria_picture) drifted from locked 24 (0x18)");
#else /* ILP32 (wasm32): pointer members shrink 8B->4B and struct/pointer
       * alignment relaxes 8->4, collapsing each struct below. GuardRecord's
       * single trailing pointer and ObjectRecord's chain of pointer members
       * (prop/model/ptr_allocated_collisiondata_block/projectile-embedment
       * union) are the only movers; ObjectRecord's ILP32 0x80 is the
       * retail-N64-matching size (retail pointers are 4B, same natural
       * alignment as ILP32) — the ACTUAL N64 layout the port's ROM reads
       * target, unlike the LP64 0x90 this TU otherwise locks. */
_Static_assert(sizeof(GuardRecord) == 28, "sizeof(GuardRecord) drifted from ILP32-derived 28 (0x1c)");
_Static_assert(sizeof(DoorRecord) == 256, "sizeof(DoorRecord) drifted from ILP32-derived 256 (0x100)");
_Static_assert(sizeof(GlobalDoorScaleRecord) == 8, "sizeof(GlobalDoorScaleRecord) drifted from locked 8 (0x8)");
_Static_assert(sizeof(ObjectRecord) == 128, "sizeof(ObjectRecord) drifted from ILP32-derived retail-matching 128 (0x80)");
_Static_assert(sizeof(WeaponObjRecord) == 136, "sizeof(WeaponObjRecord) drifted from ILP32-derived 136 (0x88)");
_Static_assert(sizeof(KeyRecord) == 132, "sizeof(KeyRecord) drifted from ILP32-derived 132 (0x84)");
_Static_assert(sizeof(TintedGlassRecord) == 148, "sizeof(TintedGlassRecord) drifted from ILP32-derived 148 (0x94)");
_Static_assert(sizeof(BodyArmourRecord) == 136, "sizeof(BodyArmourRecord) drifted from ILP32-derived 136 (0x88)");
_Static_assert(sizeof(MonitorObjRecord) == 256, "sizeof(MonitorObjRecord) drifted from ILP32-derived retail-matching 256 (0x100)");
_Static_assert(sizeof(MultiMonitorObjRecord) == 596, "sizeof(MultiMonitorObjRecord) drifted from ILP32-derived 596 (0x254)");
_Static_assert(sizeof(AutogunRecord) == 216, "sizeof(AutogunRecord) drifted from ILP32-derived 216 (0xd8)");
_Static_assert(sizeof(MultiAmmoCrateRecord) == 180, "sizeof(MultiAmmoCrateRecord) drifted from ILP32-derived 180 (0xb4)");
_Static_assert(sizeof(VehichleRecord) == 176, "sizeof(VehichleRecord) drifted from ILP32-derived 176 (0xb0)");
_Static_assert(sizeof(AircraftRecord) == 180, "sizeof(AircraftRecord) drifted from ILP32-derived 180 (0xb4)");
_Static_assert(sizeof(TankRecord) == 224, "sizeof(TankRecord) drifted from ILP32-derived 224 (0xe0)");
_Static_assert(sizeof(CCTVRecord) == 252, "sizeof(CCTVRecord) drifted from ILP32-derived 252 (0xfc)");
_Static_assert(sizeof(AmmoCrateRecord) == 132, "sizeof(AmmoCrateRecord) drifted from ILP32-derived 132 (0x84)");
_Static_assert(sizeof(SafeObjectRecord) == 20, "sizeof(SafeObjectRecord) drifted from ILP32-derived 20 (0x14)");
_Static_assert(sizeof(TagObjectRecord) == 16, "sizeof(TagObjectRecord) drifted from ILP32-derived 16 (0x10)");
_Static_assert(sizeof(RenameObjectRecord) == 40, "sizeof(RenameObjectRecord) drifted from ILP32-derived 40 (0x28)");
_Static_assert(sizeof(LinkRecord) == 16, "sizeof(LinkRecord) drifted from ILP32-derived 16 (0x10)");
_Static_assert(sizeof(SwitchRecord) == 16, "sizeof(SwitchRecord) drifted from ILP32-derived 16 (0x10)");
_Static_assert(sizeof(LockDoorRecord) == 16, "sizeof(LockDoorRecord) drifted from ILP32-derived 16 (0x10)");
_Static_assert(sizeof(struct setup_objective_text) == 16, "sizeof(struct setup_objective_text) drifted from ILP32-derived 16 (0x10)");
_Static_assert(sizeof(struct criteria_roomentered) == 16, "sizeof(struct criteria_roomentered) drifted from ILP32-derived 16 (0x10)");
_Static_assert(sizeof(struct criteria_deposit) == 20, "sizeof(struct criteria_deposit) drifted from ILP32-derived 20 (0x14)");
_Static_assert(sizeof(struct criteria_picture) == 16, "sizeof(struct criteria_picture) drifted from ILP32-derived 16 (0x10)");
#endif
/* objective_entry has no pointer member (u32/enum/u16/u8/s8 only) — width-invariant. */
_Static_assert(sizeof(struct objective_entry) == 16, "sizeof(struct objective_entry) drifted from locked 16 (0x10)");
/* StandTile / StandFile navmesh family: bitfields/u16/u32 only, no pointers — width-invariant. */
_Static_assert(sizeof(StandTilePoint) == 8, "sizeof(StandTilePoint) drifted from locked 8 (0x8)");
_Static_assert(sizeof(StandTileHeaderMid) == 2, "sizeof(StandTileHeaderMid) drifted from locked 2 (0x2)");
_Static_assert(sizeof(StandTileHeaderTail) == 2, "sizeof(StandTileHeaderTail) drifted from locked 2 (0x2)");
_Static_assert(sizeof(StandTile) == 8, "sizeof(StandTile) drifted from locked 8 (0x8)");
_Static_assert(sizeof(StandFilePoint) == 8, "sizeof(StandFilePoint) drifted from locked 8 (0x8)");
_Static_assert(sizeof(StandFileTile) == 8, "sizeof(StandFileTile) drifted from locked 8 (0x8)");

/* Union / bitfield-adjacent field offsets (FID-0036) + StandTile navmesh family.
 * KeyRecord.keyID / MultiAmmoCrateRecord.unk80+slots / TankRecord.rect all sit
 * right after the ObjectRecord chain, so they inherit ObjectRecord's LP64
 * 0x90 / ILP32 0x80 split one-for-one (TankRecord.rect additionally has its
 * own leading pointer member, unk80, ahead of it — see per-struct derivation
 * in the task report). StandTile/StandFileTile carry no pointers anywhere in
 * their layout and are left ungated. */
#if __SIZEOF_POINTER__ == 8
_Static_assert(offsetof(KeyRecord, keyID) == 144, "offsetof(KeyRecord, keyID) drifted from locked 144 (0x90)");
_Static_assert(offsetof(MultiAmmoCrateRecord, unk80) == 144, "offsetof(MultiAmmoCrateRecord, unk80) drifted from locked 144 (0x90)");
_Static_assert(offsetof(MultiAmmoCrateRecord, slots) == 144, "offsetof(MultiAmmoCrateRecord, slots) drifted from locked 144 (0x90)");
_Static_assert(offsetof(TankRecord, rect) == 152, "offsetof(TankRecord, rect) drifted from locked 152 (0x98)");
#else
_Static_assert(offsetof(KeyRecord, keyID) == 128, "offsetof(KeyRecord, keyID) drifted from ILP32-derived retail-matching 128 (0x80)");
_Static_assert(offsetof(MultiAmmoCrateRecord, unk80) == 128, "offsetof(MultiAmmoCrateRecord, unk80) drifted from ILP32-derived retail-matching 128 (0x80)");
_Static_assert(offsetof(MultiAmmoCrateRecord, slots) == 128, "offsetof(MultiAmmoCrateRecord, slots) drifted from ILP32-derived retail-matching 128 (0x80)");
_Static_assert(offsetof(TankRecord, rect) == 132, "offsetof(TankRecord, rect) drifted from ILP32-derived 132 (0x84)");
#endif
_Static_assert(offsetof(StandTile, room) == 3, "offsetof(StandTile, room) drifted from locked 3 (0x3)");
_Static_assert(offsetof(StandTile, mid) == 4, "offsetof(StandTile, mid) drifted from locked 4 (0x4)");
_Static_assert(offsetof(StandTile, tail) == 6, "offsetof(StandTile, tail) drifted from locked 6 (0x6)");
_Static_assert(offsetof(StandTile, points) == 8, "offsetof(StandTile, points) drifted from locked 8 (0x8)");
_Static_assert(offsetof(StandFileTile, room) == 3, "offsetof(StandFileTile, room) drifted from locked 3 (0x3)");
_Static_assert(offsetof(StandFileTile, mid) == 4, "offsetof(StandFileTile, mid) drifted from locked 4 (0x4)");
_Static_assert(offsetof(StandFileTile, tail) == 6, "offsetof(StandFileTile, tail) drifted from locked 6 (0x6)");
/* ==== END generated ==== */

/* The FID-0085/0087/0088/0091/0092/0094 manual locks below all test the SAME
 * underlying phenomenon: retail N64 code baked in raw byte offsets assuming
 * 4-byte pointers; on this port's LP64 build, pointer members inside
 * struct hand / struct player widen to 8 bytes, so those raw offsets no
 * longer coincide with the real (named) fields — that divergence is exactly
 * what makes the default-ON fixes load-bearing. Under ILP32 (wasm32) that
 * divergence does not exist: pointers are 4 bytes, matching retail exactly,
 * so struct hand/player collapse back to (at least very close to) the retail
 * layout the raw offsets were written against — confirmed empirically:
 * sizeof(struct hand) == 936 (the retail N64 stride) under wasm32, so the
 * FID-0094 "!=" stride check legitimately does NOT hold there. These locks
 * are therefore LP64-only: they assert that a 64-bit-pointer-widening
 * divergence exists, which is a meaningless (and false) question to ask on a
 * 32-bit pointer target. Gating the whole block out under ILP32 is not a
 * blanket-gate of convenience — every assert in it is definitionally about
 * the LP64 vs. retail-N64 pointer-width gap. */
#if __SIZEOF_POINTER__ == 8

/* ---- FID-0085: grenade-round projectile-init-matrix hand field (manual) ----
 * sub_GAME_7F05F73C (grenade launcher / flare pistol / piton gun round spawn)
 * copies the projectile init matrix from &hands[hand].throw_item_pos_related.
 * Retail US ASM reads it as the raw N64 byte offset g_CurrentPlayer + hand*936
 * + 0xAD8, i.e. hands@0x870 + field@+0x268. On the 64-bit port layout, pointer
 * fields inside struct hand (audioHandle, rocket, ...) before that field expand
 * 4->8B, so the field is NOT at N64 0x268 and the hand stride is NOT 936. The
 * native gun.c body (post-fix) MUST reach it by C field access, never the raw
 * offset. These asserts lock the actual PC layout and, critically, prove the
 * raw N64 offset the legacy (GE007_NO_PROJECTILE_INIT_MTX_FIX) path uses does
 * NOT coincide with the real field — so the default-ON fix is load-bearing.
 * Regenerate expected values with tools/fidelity/gen_struct_asserts.py if the
 * layout intentionally changes; a drift here is a fix-invalidating finding. */
#define FID0085_N64_HAND_STRIDE   936     /* ASM *936 strength-reduce            */
#define FID0085_N64_HANDS_BASE    0x870   /* addiu $t9,$t8,0x870                 */
#define FID0085_N64_MTX_FIELD     0x268   /* 0xAD8 - 0x870 (raw path within-hand)*/
_Static_assert(sizeof(struct hand) == 968,
    "sizeof(struct hand) drifted from locked 968 (0x3c8) — FID-0085 stride lock");
_Static_assert(offsetof(struct hand, throw_item_pos_related) == 0x274,
    "offsetof(struct hand, throw_item_pos_related) drifted from locked 0x274 — FID-0085");
_Static_assert(offsetof(struct hand, throw_item_pos_related) != FID0085_N64_MTX_FIELD,
    "native throw_item_pos_related coincides with the raw N64 0x268 offset — "
    "the legacy raw+0xAD8 read would be correct and the FID-0085 fix moot; re-derive");
_Static_assert(sizeof(struct hand) != FID0085_N64_HAND_STRIDE,
    "native hand stride equals the N64 936 — per-hand raw stride would be correct; re-derive");

/* ---- FID-0087: grenade-round projectile SPAWN POSITION hand field ----
 * sub_GAME_7F05F73C passes the spawn position as retail hand+0x2E8 = field_B58.
 * On the 64-bit layout pointer fields inside struct hand before field_B58 expand
 * 4->8B (+0xC), so it sits at native 0x2F4 not 0x2E8; the legacy raw read
 * (GE007_NO_GRENADE_SPAWN_POS_FIX) would land on field_B4C/B50/B54. */
#define FID0087_N64_POS_FIELD  0x2E8   /* raw (u8*)hand + 0x2E8 legacy read */
_Static_assert(offsetof(struct hand, field_B58) == 0x2F4,
    "offsetof(struct hand, field_B58) drifted from locked 0x2F4 — FID-0087");
_Static_assert(offsetof(struct hand, field_B58) != FID0087_N64_POS_FIELD,
    "native field_B58 coincides with the raw N64 hand+0x2E8 offset — the legacy "
    "raw read would be correct and the FID-0087 fix moot; re-derive");

/* ---- FID-0088 / FID-0092 / FID-0093: post-hands PLAYER fields read/written via
 * raw N64 byte offsets in the legacy paths. The hands[] array grows on the
 * 64-bit layout (per-hand 936->968 + pre-hands pointer growth), shifting every
 * field after hands[] by a single uniform delta, so NONE of these fields sit at
 * their raw N64 offset. A `==` here would mean the raw read/write coincides with
 * the real field and the default-ON fix is moot -> a fix-invalidating drift. */
#define FID0088_N64_TILECOLOR      0xFDC   /* raw (u8*)g_CurrentPlayer + 0xFDC  */
#define FID0091_N64_LASTZTRIGGER   0x105C  /* raw (u8*)g_CurrentPlayer + 0x105C */
#define FID0092_N64_GUNAMMOOFF     0x1064  /* raw (u8*)g_CurrentPlayer + 0x1064 */
_Static_assert(offsetof(struct player, tileColor) != FID0088_N64_TILECOLOR,
    "native player.tileColor coincides with raw N64 0xFDC — FID-0088 fix moot; re-derive");
_Static_assert(offsetof(struct player, last_z_trigger_timer) != FID0091_N64_LASTZTRIGGER,
    "native player.last_z_trigger_timer coincides with raw N64 0x105C — FID-0092 fix moot");
_Static_assert(offsetof(struct player, gunammooff) != FID0092_N64_GUNAMMOOFF,
    "native player.gunammooff coincides with raw N64 0x1064 — FID-0093 fix moot");
/* The post-hands shift is a single uniform delta (one hands[] growth event): */
_Static_assert(offsetof(struct player, last_z_trigger_timer) - FID0091_N64_LASTZTRIGGER
            == offsetof(struct player, tileColor) - FID0088_N64_TILECOLOR,
    "post-hands native shift not uniform (tileColor vs last_z_trigger_timer)");
_Static_assert(offsetof(struct player, gunammooff) - FID0092_N64_GUNAMMOOFF
            == offsetof(struct player, tileColor) - FID0088_N64_TILECOLOR,
    "post-hands native shift not uniform (tileColor vs gunammooff)");

/* ---- FID-0094: MP other-player beam/aim tick (bondview.c playerTickBeams) reads
 * and writes struct player through raw N64 byte offsets and indexes hands[] with
 * the N64 936-byte stride. ROOT-CAUSED, code fix pending (playerTickBeams lives in
 * bondview.c). These locks pin the correct native mapping the fix must use AND
 * prove the raw offsets the live code uses cannot be right on the 64-bit layout:
 *   - firing flags: retail raw player+0x875 / +0xC1D are hands[0]/hands[1]
 *     .weapon_firing_status (gun.c:1949 accesses the same field by name); the two
 *     raws are one N64 hand-stride (0x3A8 = 936) apart.
 *   - hand-position source: retail raw player + i*936 + 0xB50 is hands[i].field_B50.
 *   - the beam loop's srcOff strength-reduces to i*936 = the N64 sizeof(struct hand);
 *     native is 968 (locked above), so hand 1's source mis-indexes.
 * An `==` on any lock below means the raw access coincides with the real field and
 * the divergence is illusory -> re-derive. */
#define FID0094_N64_HAND0_FIRING  0x875   /* lb player+0x875 (7F08BE40)  */
#define FID0094_N64_HAND1_FIRING  0xC1D   /* lb player+0xC1D (7F08BE54)  */
#define FID0094_N64_HAND_STRIDE   936     /* srcOff strength-reduce = i*936 */
#define FID0094_N64_HAND0_SRCPOS  0xB50   /* lwc1 player+0xB50 (7F08BEF0) */
_Static_assert(offsetof(struct player, hands) + offsetof(struct hand, weapon_firing_status)
               != FID0094_N64_HAND0_FIRING,
    "native hands[0].weapon_firing_status coincides with raw N64 0x875 — FID-0094 moot; re-derive");
_Static_assert(offsetof(struct player, hands) + offsetof(struct hand, weapon_firing_status)
               + sizeof(struct hand) != FID0094_N64_HAND1_FIRING,
    "native hands[1].weapon_firing_status coincides with raw N64 0xC1D — FID-0094 moot; re-derive");
_Static_assert(offsetof(struct player, hands) + offsetof(struct hand, field_B50)
               != FID0094_N64_HAND0_SRCPOS,
    "native hands[0].field_B50 coincides with raw N64 0xB50 — FID-0094 moot; re-derive");
_Static_assert(sizeof(struct hand) != FID0094_N64_HAND_STRIDE,
    "native hand stride equals the N64 936 beam-loop srcOff — FID-0094 stride moot; re-derive");
/* The two firing raws are exactly one N64 hand-stride apart (0xC1D-0x875==936). */
_Static_assert(FID0094_N64_HAND1_FIRING - FID0094_N64_HAND0_FIRING == FID0094_N64_HAND_STRIDE,
    "FID-0094 firing-flag raws are not one N64 hand stride apart — re-read ASM");

#endif /* __SIZEOF_POINTER__ == 8 — FID-0085/0087/0088/0091/0092/0094 LP64-only */

int main(void) {
    /* If this TU compiled at all, every _Static_assert above held. The runtime
     * body exists only so the ctest has something to link and run. */
#if __SIZEOF_POINTER__ == 8
    printf("test_struct_layout: PASS (45 layout asserts + FID-0085 hand-matrix "
           "lock + FID-0087/0088/0091/0092 raw-cast field locks + FID-0094 MP "
           "beam/aim raw-offset locks held at compile time)\n");
#else
    printf("test_struct_layout: PASS (ILP32/wasm32 — 45 layout asserts with ILP32 "
           "twins held at compile time; FID-0085/0087/0088/0091/0092/0094 LP64-only "
           "pointer-widening-divergence locks skipped, not applicable on a 32-bit "
           "pointer target)\n");
#endif
    return 0;
}
